# Generated by Django 5.0 on 2023-12-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
