# Generated by Django 5.0 on 2024-01-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_remove_cart_cprice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
